[project]
name = "sinv-textconv"
requires-python = ">=3.10"
description = "A CLI toolkit for handling Sphinx inventory files."
authors = [{ name = 'Sam Vente', email = 'savente93@proton.me' }]
classifiers = [
  "Programming Language :: Rust",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Documentation :: Sphinx",
  "Topic :: Software Development :: Documentation",
  "Framework :: Sphinx",
]
keywords = ["sphinx", "objects.inv", "documentation", "cli"]

readme        = { file = "README.md", content-type = "text/markdown" }
license-files = ["LICENSE"]
dynamic       = ["version"]

[project.urls]
Homepage = 'https://github.com/aslowwriter/sinv-textconv'
Source = 'https://github.com/aslowwriter/sinv-textconv'

[build-system]
requires      = ["maturin>=1.9,<2"]
build-backend = "maturin"

[tool.maturin]
bindings      = "bin"
manifest-path = "Cargo.toml"
module-name   = "sinv-textconv"
